### ISSUE TITLE
Question on wording

### ISSUE THREAD

**Issue by sabas** [mapschool/mapschool#40]
We are translating Mapschool in Italian. I have a question:
- the question is: In second paragraph, how should we interpret the phrase "t is important that data is not specific to a certain usage" ?

and a suggestion: this phrase

```
The two formats are commonly used together, like in the case of satellite images as raster data with vector data roads overlaid.
```

was adapted as

```
The two formats are commonly used together, like in the case of satellite images (raster data) with roads overlaid (vector data).
```

**Comment by morganherlocker** [comment]
I could see that phrase being interpreted in two ways:
1. Data should be thought of in the abstract, not as a specific implementation of a data format.

or
1. The data used to create a map or visualization is distinct from the map or visualization itself.

The first emphasizes the need to decouple data from proprietary format like kml, or more commonly, shapefiles (people often conflate spatial data with the proprietary shapefile format in my experience).  The second emphasizes the fact that the same data can be visualized in many ways. Perhaps both meanings should be included, since I think they both tackle common misconceptions. 2 is especially important though, since a novice might very well think that a map is just an image rather than a rendering of non-visual data.

**Comment by tmcw** [comment]
The parsing

> The two formats are commonly used together, like in the case of satellite images (raster data) with roads overlaid (vector data).

Seems correct and straightforward, though the original phrasing is really awkward. Would this be an improvement?

> The two types are often combined, like when vector road data is overlaid over raster satellite data.

**Comment by sabas** [comment]
@tmcw yes, I think it's better

@morganherlocker to synthesize your interpretation

> Maps are fundamentally composed of data. Data are abstract entities, composed of billions of points or just a few polygons, or a photo-like recording of colors and temperature: they are the source -in whatever format they are initally presented- from which comes the map

**Comment by tmcw** [comment]
Cool - I think we're good here.
