### ISSUE TITLE
Heatmap is not a form of interpolation

### ISSUE THREAD

**Issue by tmcw** [mapschool/mapschool#50]
> Heatmap is not a method of spatial interpolation, in fact I think the mapschool here is referring to density estimation which is not interpolation at all.....although, Heatmap is a visual metaphor that could be used for interpolated surfaces of course

Came in via Wufoo. If not interpolation, then what is it? We could just not mention heatmaps, but they're a very common type and common lingo, so it would be a shame not to explain or frame them at all.

**Comment by morganherlocker** [comment]
This is a tricky one. I tend to think of a heatmap as a rough interpolation method, but I can think of plenty of reasons why one would not. 

Heatmaps are often built purely off of density, which would not really be an interpolation, but this is not always the case. Building a heatmap off of a z value (as the commenter points out) is definitely a form of interpolation. In fact, a z-weighted heatmap is pretty much the same thing as isobands/contours (but on a gradient instead of hard breaks), which is interpolation in its purest. 

IMO heatmaps are essential, and perhaps the topic warrants its own section? They are widely used, but also misused all over the place.

**Comment by Bakelly** [comment]
Here the phrase "...ways to interpolate..." can seem to imply "...method to interpolate...", which I think is bothering the OP.

To me, a "Heatmap" is a generalized or even colloquial term used to describe the visualization of an interpolated surface.  I think this section could be "Types of Interpolated Data" (Heatmaps, Isolines...) and "Methods of Interpolation" (Kriging, IDW, Natural Neighbor...), but that seems too detailed for the page at this time.

Perhaps simply changing
"There are many ways to interpolate point data:"
to
"There are many examples of interpolated data:"

**Comment by tmcw** [comment]
Thought about rephrasings, not seeing a good one that's clearer but not wordy. Happy to accept a PR if someone has a better way to write this section.
